// Static cover data — fallback when Supabase is unavailable
export const STATIC_COVERS = [
  {
    id: 1,
    title: "The Dark Side of the Moon",
    musician: "Pink Floyd",
    coverArtist: "Storm Thorgerson",
    role: "Art Direction",
    year: 1973,
    label: "Harvest",
    genre: ["Rock"],
    curatorNote: "Thorgerson's prism design is perhaps the most recognized album cover in history — minimal, bold, and endlessly imitated.",
    spotifyId: "4LH4d3cOWNNsVw41Gqt2kv",
    hue: 220, sat: 10, lit: 12
  },
  {
    id: 2,
    title: "Abbey Road",
    musician: "The Beatles",
    coverArtist: "Iain Macmillan",
    role: "Photography",
    year: 1969,
    label: "Apple",
    genre: ["Rock"],
    curatorNote: "A single crosswalk photograph became one of the most parodied images in music. Macmillan had ten minutes and six shots.",
    spotifyId: "0ETFjACtuP2ADo6LFhL6HN",
    hue: 200, sat: 15, lit: 60
  },
  {
    id: 3,
    title: "Kind of Blue",
    musician: "Miles Davis",
    coverArtist: "Jay Maisel",
    role: "Photography",
    year: 1959,
    label: "Columbia",
    genre: ["Jazz"],
    curatorNote: "Maisel's close-up of Davis, eyes shut in concentration, perfectly mirrors the introspective cool of the music inside.",
    spotifyId: "1weenld61qoidwYuZ1GESA",
    hue: 220, sat: 40, lit: 30
  },
  {
    id: 4,
    title: "A Love Supreme",
    musician: "John Coltrane",
    coverArtist: "Bob Thiele",
    role: "Art Direction",
    year: 1965,
    label: "Impulse!",
    genre: ["Jazz"],
    curatorNote: "The stark portrait with hand-lettered title evokes the spiritual intensity of Coltrane's masterwork.",
    spotifyId: "7Eoz7hJvaX1eFkbpQxC5PA",
    hue: 30, sat: 60, lit: 25
  },
  {
    id: 5,
    title: "Selected Ambient Works 85–92",
    musician: "Aphex Twin",
    coverArtist: "Paul Nicholson",
    role: "Illustration",
    year: 1992,
    label: "Apollo",
    genre: ["Electronic"],
    curatorNote: "The minimal geometric logo against deep blue became a totem for the ambient electronic movement.",
    spotifyId: "7aNclGRxTysfh6z0d8671k",
    hue: 240, sat: 50, lit: 18
  },
  {
    id: 6,
    title: "Homework",
    musician: "Daft Punk",
    coverArtist: "Alex & Martin",
    role: "Art Direction",
    year: 1997,
    label: "Virgin",
    genre: ["Electronic"],
    curatorNote: "Clean modernist typography over textured metal — the cover channeled the anonymous machine aesthetic that defined the duo.",
    spotifyId: "5uRdvUR7xCnHmUW8n64n9y",
    hue: 0, sat: 0, lit: 25
  },
  {
    id: 7,
    title: "Illmatic",
    musician: "Nas",
    coverArtist: "Danny Clinch",
    role: "Photography",
    year: 1994,
    label: "Columbia",
    genre: ["Hip-hop"],
    curatorNote: "The superimposed child portrait over the Queensbridge projects is a visceral map of origin — haunting and beautiful.",
    spotifyId: "3kEtdS2pH6hKcMU9Wioob1",
    hue: 35, sat: 50, lit: 35
  },
  {
    id: 8,
    title: "Madvillainy",
    musician: "Madvillain",
    coverArtist: "Jeff Jank",
    role: "Illustration",
    year: 2004,
    label: "Stones Throw",
    genre: ["Hip-hop"],
    curatorNote: "Jank's comic-book style perfectly captured the off-kilter, villainous persona of DOOM and Madlib's collaboration.",
    spotifyId: "1EHSCvNFbcs0ADjoNB014v",
    hue: 340, sat: 50, lit: 28
  },
  {
    id: 9,
    title: "Blade Runner (Original Soundtrack)",
    musician: "Vangelis",
    coverArtist: "John Alvin",
    role: "Illustration",
    year: 1982,
    label: "Full Moon",
    genre: ["Soundtracks"],
    curatorNote: "The neon-drenched cityscape painting mirrors the film's dystopian beauty and became inseparable from the music.",
    spotifyId: "6NkuCdMz5tGmHbOXAWbtCW",
    hue: 260, sat: 55, lit: 22
  },
  {
    id: 11,
    title: "Head Hunters",
    musician: "Herbie Hancock",
    coverArtist: "Victor Moscoso",
    role: "Illustration",
    year: 1973,
    label: "Columbia",
    genre: ["Jazz"],
    curatorNote: "Moscoso's psychedelic illustration of Hancock as a mechanical shaman bridges jazz, funk, and the counterculture.",
    spotifyId: "5fmIolILp5NAtNYiRPjhzA",
    hue: 120, sat: 50, lit: 30
  },
  {
    id: 12,
    title: "Random Access Memories",
    musician: "Daft Punk",
    coverArtist: "Warren Fu",
    role: "Art Direction",
    year: 2013,
    label: "Columbia",
    genre: ["Electronic"],
    curatorNote: "The chrome helmets shot with analog precision — Fu's art direction married retro-futurism with pristine execution.",
    spotifyId: "4m2880jivSbbyEGAKfITCa",
    hue: 40, sat: 70, lit: 35
  },
  {
    id: 13,
    title: "Remain in Light",
    musician: "Talking Heads",
    coverArtist: "Tibor Kalman",
    role: "Art Direction",
    year: 1980,
    label: "Sire",
    genre: ["Rock"],
    curatorNote: "Kalman's collaged, digitally warped portraits anticipated the fractured identity themes of the internet age by decades.",
    spotifyId: "1JvXxLsm0PxlGH4LXzqMGq",
    hue: 0, sat: 75, lit: 45
  },
  {
    id: 14,
    title: "Interstellar (Original Soundtrack)",
    musician: "Hans Zimmer",
    coverArtist: "Lee Nutter",
    role: "Photography",
    year: 2014,
    label: "WaterTower",
    genre: ["Soundtracks"],
    curatorNote: "The vast cosmic imagery against pitch black channels the film's awe — Zimmer's organs seem to resonate visually.",
    spotifyId: "7a78GiEowpaCa7ZJs44xUU",
    hue: 30, sat: 20, lit: 10
  },
  {
    id: 15,
    title: "To Pimp a Butterfly",
    musician: "Kendrick Lamar",
    coverArtist: "Denis Rouvre",
    role: "Photography",
    year: 2015,
    label: "TDE",
    genre: ["Hip-hop"],
    curatorNote: "Rouvre's group portrait on the White House lawn is confrontational, celebratory, and historically charged all at once.",
    spotifyId: "7ycBtnsMtyVbbwTfJwRjSP",
    hue: 45, sat: 30, lit: 40
  },
  {
    id: 16,
    title: "El Madrileño",
    musician: "C. Tangana",
    coverArtist: "Santos Bacana",
    role: "Photography",
    contributors: [
      { name: "Santos Bacana", role: "Photography" },
      { name: "Ivan Floro", role: "Illustration" }
    ],
    year: 2021,
    label: "Sony",
    genre: ["Hip-hop", "Pop"],
    curatorNote: "Bacana's tabloid-style portrait — cigarette, gold chains, raw swagger — turned C. Tangana into a pop-culture painting of modern Madrid.",
    spotifyId: "52QyC9nSbgtHFXyQRHsXJ9",
    hue: 25, sat: 55, lit: 45
  },
  {
    id: 17,
    title: "La Cantera",
    musician: "Guitarricadelafuente",
    coverArtist: "Koln Studio",
    role: "Art Direction",
    year: 2022,
    label: "Universal",
    genre: ["Pop"],
    curatorNote: "The painterly, sun-drenched aesthetic channels Mediterranean warmth and nostalgia — a visual love letter to southern Spain.",
    spotifyId: "3BDwyojdwMAmBEsXZlyQjW",
    hue: 40, sat: 65, lit: 55
  },
  {
    id: 18,
    title: "MOTOMAMI",
    musician: "Rosalía",
    coverArtist: "Filip Custic",
    role: "Photography",
    year: 2022,
    label: "Columbia",
    genre: ["Pop", "Electronic"],
    curatorNote: "Custic's clinical, hyper-stylized portrait strips pop stardom to its raw, confrontational core — a selfie as manifesto.",
    spotifyId: "6jbtHi5R0jMXoliU2OS0lo",
    hue: 0, sat: 0, lit: 90
  },
  {
    id: 20,
    title: "OK Computer",
    musician: "Radiohead",
    coverArtist: "Stanley Donwood",
    role: "Illustration",
    year: 1997,
    label: "Parlophone",
    genre: ["Rock"],
    curatorNote: "Donwood's layered collage of highways and digital noise became the defining visual of late-90s technological anxiety.",
    spotifyId: "6dVIqQ8qmQ5GBnJ9shOYGE",
    hue: 200, sat: 10, lit: 70
  },
  {
    id: 21,
    title: "Blonde",
    musician: "Frank Ocean",
    coverArtist: "Wolfgang Tillmans",
    role: "Photography",
    year: 2016,
    label: "Boys Don't Cry",
    genre: ["Hip-hop", "Pop"],
    curatorNote: "Tillmans' shower-drenched, green-haired portrait is vulnerability made visible — intimate, blurred, deliberately imperfect.",
    spotifyId: "3mH6qwIy9crq0I9YQbOuDf",
    hue: 120, sat: 35, lit: 55
  },
  {
    id: 22,
    title: "Wish You Were Here",
    musician: "Pink Floyd",
    coverArtist: "Storm Thorgerson",
    role: "Photography",
    year: 1975,
    label: "Harvest",
    genre: ["Rock"],
    curatorNote: "Two businessmen shaking hands, one on fire — Thorgerson's surrealist comment on the music industry remains searingly relevant.",
    spotifyId: "0bCAjiUamIFqKJsekOYuRw",
    hue: 210, sat: 40, lit: 50
  },
  {
    id: 23,
    title: "Discovery",
    musician: "Daft Punk",
    coverArtist: "Leiji Matsumoto",
    role: "Illustration",
    year: 2001,
    label: "Virgin",
    genre: ["Electronic"],
    curatorNote: "Matsumoto's anime-inspired chrome reflection merged French house with Japanese pop art — a genre collision in a single image.",
    spotifyId: "2noRn2Aes5aoNVsU6iWThc",
    hue: 220, sat: 60, lit: 30
  },
  {
    id: 24,
    title: "My Beautiful Dark Twisted Fantasy",
    musician: "Kanye West",
    coverArtist: "George Condo",
    role: "Illustration",
    year: 2010,
    label: "Roc-A-Fella",
    genre: ["Hip-hop"],
    curatorNote: "Condo's grotesque-beautiful painting — pixelated for controversy — blurred the line between fine art and album packaging forever.",
    spotifyId: "20r762YmB5HeofjMCiPMLv",
    hue: 350, sat: 60, lit: 30
  },
  {
    id: 25,
    title: "In Rainbows",
    musician: "Radiohead",
    coverArtist: "Stanley Donwood",
    role: "Illustration",
    year: 2007,
    label: "XL",
    genre: ["Rock"],
    curatorNote: "Explosive color bursts over void black — Donwood's most painterly work mirrors the album's dynamic range from whisper to roar.",
    spotifyId: "5vkqYmiPBYLaalcmjujWxK",
    hue: 15, sat: 80, lit: 45
  },
  {
    id: 26,
    title: "Currents",
    musician: "Tame Impala",
    coverArtist: "Robert Beatty",
    role: "Illustration",
    year: 2015,
    label: "Modular",
    genre: ["Rock", "Electronic"],
    curatorNote: "Beatty's swirling vortex of liquid chrome perfectly visualizes the album's theme of unstoppable personal transformation.",
    spotifyId: "79dL7FLiJFOO0EoehUHQBv",
    hue: 300, sat: 50, lit: 40
  },
  {
    id: 28,
    title: "The Miseducation of Lauryn Hill",
    musician: "Lauryn Hill",
    coverArtist: "Ernie Paniccioli",
    role: "Photography",
    year: 1998,
    label: "Ruffhouse",
    genre: ["Hip-hop"],
    curatorNote: "Paniccioli's etched-wood portrait reframes a hip-hop icon as timeless folk art — education, identity, and resistance in one frame.",
    spotifyId: "1BZoqf8Zje5nGdwZhOjAtD",
    hue: 35, sat: 50, lit: 30
  },
  {
    id: 29,
    title: "SEIS",
    musician: "Mon Laferte",
    coverArtist: "Mon Laferte",
    role: "Illustration",
    year: 2021,
    label: "Universal",
    genre: ["Pop"],
    curatorNote: "Laferte painted her own cover — a self-portrait that doubles as emotional autobiography, raw and unapologetically Latina.",
    spotifyId: "3EOGXDmeHGGlAFAIlagcDF",
    hue: 350, sat: 55, lit: 40
  },
  {
    id: 30,
    title: "El Mal Querer",
    musician: "Rosalía",
    coverArtist: "Filip Custic",
    role: "Photography",
    year: 2018,
    label: "Columbia",
    genre: ["Pop", "Electronic"],
    curatorNote: "Custic's hyper-real, almost surgical aesthetic — red nails, clinical pose — announced a new visual language for flamenco's future.",
    spotifyId: "355bjCHzRJztCzaG5Za4gq",
    hue: 0, sat: 70, lit: 35
  },
  {
    id: 31,
    title: "Nevermind",
    musician: "Nirvana",
    coverArtist: "Kirk Weddle",
    role: "Photography",
    year: 1991,
    label: "DGC",
    genre: ["Rock"],
    curatorNote: "Weddle's underwater baby shot became the defining image of the '90s — raw, provocative, and impossible to forget.",
    spotifyId: "6okv1avxEgYSdc2JYy6ZEi",
    hue: 200, sat: 60, lit: 45
  },
  {
    id: 32,
    title: "IGOR",
    musician: "Tyler, the Creator",
    coverArtist: "Felicia Tomasko",
    role: "Photography",
    year: 2019,
    label: "Columbia",
    genre: ["Hip-hop"],
    curatorNote: "The pink-wigged alter ego cover is as genre-bending as the music — pop art meets soul, styled to perfection.",
    spotifyId: "5zi7WsKlIiUXv09tbGLKsE",
    hue: 340, sat: 50, lit: 55
  },
  {
    id: 33,
    title: "Un Verano Sin Ti",
    musician: "Bad Bunny",
    coverArtist: "Stillz",
    role: "Photography",
    year: 2022,
    label: "Rimas",
    genre: ["Pop", "Hip-hop"],
    curatorNote: "Sunlit, lo-fi intimacy — a phone-camera aesthetic that turned reggaetón packaging into something diaristic and personal.",
    spotifyId: "3RQQmkQEvNCY4prGKE6oc5",
    hue: 200, sat: 50, lit: 60
  },
  {
    id: 34,
    title: "WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?",
    musician: "Billie Eilish",
    coverArtist: "Kenneth Cappello",
    role: "Photography",
    year: 2019,
    label: "Interscope",
    genre: ["Pop"],
    curatorNote: "White-eyed and grinning in the dark — Cappello's portrait distilled Gen-Z horror-pop into a single unsettling frame.",
    spotifyId: "0S0KGZnfBGSIssfF54WSJh",
    hue: 160, sat: 30, lit: 20
  },
  {
    id: 35,
    title: "AM",
    musician: "Arctic Monkeys",
    coverArtist: "Matt Helders",
    role: "Illustration",
    year: 2013,
    label: "Domino",
    genre: ["Rock"],
    curatorNote: "A sine wave on black — Helders' minimalist sound visualization is as lean and precise as the riffs inside.",
    spotifyId: "6645HGh7ZOZSUTpqW9iYLR",
    hue: 0, sat: 0, lit: 10
  },
  {
    id: 36,
    title: "After Hours",
    musician: "The Weeknd",
    coverArtist: "Anton Tammi",
    role: "Photography",
    year: 2020,
    label: "XO / Republic",
    genre: ["Pop", "Electronic"],
    curatorNote: "Blood-smeared and neon-lit — Tammi's portrait captures the album's descent into late-night excess with cinematic precision.",
    spotifyId: "4yP0hdKOZPNshxUOjY0cZj",
    hue: 0, sat: 70, lit: 30
  },
  {
    id: 37,
    title: "Lemonade",
    musician: "Beyoncé",
    coverArtist: "Robin Harper",
    role: "Photography",
    year: 2016,
    label: "Parkwood / Columbia",
    genre: ["Pop", "Hip-hop"],
    curatorNote: "Harper's visual narrative transformed the album into a full art installation — every frame a painting of resilience.",
    spotifyId: "7dK54iZuOxXFarGhXwEXfF",
    hue: 45, sat: 50, lit: 40
  },
  {
    id: 38,
    title: "ASTROWORLD",
    musician: "Travis Scott",
    coverArtist: "David LaChapelle",
    role: "Photography",
    year: 2018,
    label: "Epic / Cactus Jack",
    genre: ["Hip-hop"],
    curatorNote: "LaChapelle built a surreal theme park entrance from Travis's head — maximalist, psychedelic, and instantly iconic.",
    spotifyId: "41GuZcammIkupMPKH2OJ6I",
    hue: 30, sat: 60, lit: 35
  },
  {
    id: 39,
    title: "Demon Days",
    musician: "Gorillaz",
    coverArtist: "Jamie Hewlett",
    role: "Illustration",
    year: 2005,
    label: "Parlophone",
    genre: ["Electronic", "Rock"],
    curatorNote: "Hewlett's four cartoon faces against pitch black — the virtual band's finest visual moment, eerie and magnetic.",
    spotifyId: "0bUTHlWbkSQysoM3VsWldT",
    hue: 0, sat: 0, lit: 15
  },
  {
    id: 40,
    title: "Aladdin Sane",
    musician: "David Bowie",
    coverArtist: "Brian Duffy",
    role: "Photography",
    year: 1973,
    label: "RCA",
    genre: ["Rock"],
    curatorNote: "Duffy's lightning-bolt portrait is the single most recognizable image in rock — glam, alien, and eternal.",
    spotifyId: "10gbq3XvTrtUSplDoTtsOb",
    hue: 0, sat: 60, lit: 45
  },
  {
    id: 41,
    title: "Unknown Pleasures",
    musician: "Joy Division",
    coverArtist: "Peter Saville",
    role: "Art Direction",
    year: 1979,
    label: "Factory",
    genre: ["Rock", "Electronic"],
    curatorNote: "Saville turned a pulsar chart into design history — white lines on black that launched a thousand t-shirts.",
    spotifyId: "5Dgqy4bBg09Rdw7CQM545s",
    hue: 0, sat: 0, lit: 5
  },
  {
    id: 42,
    title: "Rumours",
    musician: "Fleetwood Mac",
    coverArtist: "Herbert Worthington",
    role: "Photography",
    year: 1977,
    label: "Warner Bros.",
    genre: ["Rock"],
    curatorNote: "Worthington's ethereal portrait of Stevie and Mick captures the band's tangled romance in a single flowing frame.",
    spotifyId: "1bt6q2SruMsBtcerNVtpZB",
    hue: 0, sat: 0, lit: 20
  },
  {
    id: 43,
    title: "Back to Black",
    musician: "Amy Winehouse",
    coverArtist: "Bryan Adams",
    role: "Photography",
    year: 2006,
    label: "Island",
    genre: ["Jazz", "Pop"],
    curatorNote: "Adams' stark monochrome portrait — beehive, eyeliner, defiance — distilled Winehouse's retro-soul persona into pure icon.",
    spotifyId: "097eYvf9NKjFnv4xA9s2oV",
    hue: 0, sat: 0, lit: 25
  },
  {
    id: 44,
    title: "Mezzanine",
    musician: "Massive Attack",
    coverArtist: "Tom Hingston",
    role: "Art Direction",
    year: 1998,
    label: "Virgin",
    genre: ["Electronic"],
    curatorNote: "Hingston's macro beetle photograph is as dark and textured as the trip-hop within — nature made menacing.",
    spotifyId: "49MNmJhZQewjt06rpwp6QR",
    hue: 0, sat: 0, lit: 10
  },
  {
    id: 45,
    title: "Homogenic",
    musician: "Björk",
    coverArtist: "Alexander McQueen & Nick Knight",
    role: "Art Direction",
    year: 1997,
    label: "One Little Indian",
    genre: ["Electronic"],
    curatorNote: "McQueen's warrior collar and Knight's otherworldly lens — fashion, technology, and Iceland fused into one alien portrait.",
    spotifyId: "0HMsmYvoT1h2x1C4di5faf",
    hue: 210, sat: 30, lit: 35
  }
];
